---
- name: Base setup for all servers
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install common packages
      apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - ca-certificates
          - gnupg
          - lsb-release
          - openjdk-17-jdk
          - docker.io
        state: present

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
